delvtech/hyperdrive

.github/workflows/rust_test.yml, contracts/src/deployers/HyperdriveDeployerCoordinator.sol, contracts/src/deployers/erc4626/ERC4626HyperdriveDeployerCoordinator.sol, contracts/src/deployers/steth/StETHHyperdriveDeployerCoordinator.sol, contracts/src/factory/HyperdriveFactory.sol, contracts/src/interfaces/IHyperdriveDeployerCoordinator.sol, contracts/src/interfaces/IHyperdriveFactory.sol, contracts/src/interfaces/ILido.sol, contracts/src/internal/HyperdriveBase.sol, contracts/test/MockHyperdriveDeployer.sol, crates/test-utils/src/chain/test_chain.rs, test/instances/erc4626/ERC4626Hyperdrive.t.sol, test/instances/erc4626/ERC4626Validation.t.sol, test/instances/erc4626/UsdcERC4626.t.sol, test/instances/steth/StETHHyperdrive.t.sol, test/integrations/deployers/DeployerCoordinator.t.sol, test/integrations/factory/HyperdriveFactory.t.sol, test/utils/HyperdriveTest.sol
This PR makes it possible for the HyperdriveFactory to initialize with either `options.asBase = true` or `options.asBase = false`. Since it is cumbersome for the factory to handle vault shares (think about the case of Lido shares for an example), this PR moves the initialization logic into the deployer coordinators since deployer coordinators are tightly coupled to yield sources and can include bespoke logic.
=> Support more options in the factory

contracts/src/internal/HyperdriveLong.sol, contracts/src/internal/HyperdriveShort.sol, test/integrations/hyperdrive/SandwichTest.t.sol
Fixes: #769.
There are more details in the issue, but the TL;DR is that this is an exceptional edge case with zero fees. Both cases were addressed by adding a curve fee of `0.0001e18`.
=> Fixed an intermittent failure in the sandwich test

contracts/src/external/Hyperdrive.sol, contracts/src/external/HyperdriveTarget2.sol, contracts/src/external/HyperdriveTarget4.sol, contracts/src/interfaces/IHyperdrive.sol, contracts/src/libraries/HyperdriveMath.sol, contracts/src/libraries/LPMath.sol, test/units/hyperdrive/UpdateLiquidityTest.t.sol
This PR adds more comprehensive liveness checks throughout the codebase. This will further reduce the chance of arithmetic errors resulting in liveness failures during the checkpoint process.
=> Liveness Fixes

crates/hyperdrive-math/src/lp.rs, crates/hyperdrive-math/src/utils.rs
This calculation fixes the broken calculation for `Available Liquidity` on the frontend.
=> Add `calculate_idle_share_reserves` to rust sdk

contracts/src/deployers/HyperdriveDeployerCoordinator.sol, test/integrations/factory/HyperdriveFactory.t.sol
This bug resulted in the `sweepCollector` address not being set in deployments. 
Major h/t to @slundqui for finding this.
=> Fixed a bug in the deployer coordinator

contracts/src/instances/ezeth/EzETHTarget0.sol, contracts/src/interfaces/IEzETHHyperdriveRead.sol, test/instances/ezETH/EzETHHyperdrive.t.sol
Add `renzo()` and `ezETH` getters so that the main entrypoint contract is publicly accessible from the ezETH implementation of hyperdrive.  Note that for this implementation, the vault differs from that of lido in that the token `ezETH` is separate from the vault, `renzo`
=> Add `renzo()` and `ezETH()` getters

CODEOWNERS
This PR adds @mcclurejt as a global codeowner and @dpaiton, @slundqui, and @ryangoree as Rust SDK code owners. We have faced review bottlenecks recently, and distributing the review burden will help to alleviate these issues while maintaining a high bar to merge PRs.
=> Updated the CODEOWNERS file

CODEOWNERS
I noticed that @dpaiton wasn't able to approve one of my earlier PRs even though he should be a codeowner. This update makes the file more consistent with Github's example and also fixes an issue that would have prevented the global codeowners from approving changes made to the Rust SDK.
=> Updated the codeowners file to be more permissive

crates/hyperdrive-math/src/lib.rs, crates/hyperdrive-math/src/long/close.rs, crates/hyperdrive-math/src/long/fees.rs, crates/hyperdrive-math/src/lp.rs, crates/hyperdrive-math/src/short/close.rs, crates/hyperdrive-math/src/short/fees.rs
This PR unifies the calculation of `normalized_time_remaining` into a `calculate_normalized_time_remaining` method based on current time and maturity time. 
This allows other sdk methods like `close_long()` and `close_short()` to take in current time and maturity time as arguments and return accurate price quotes.
=> Calculate `normalized_time_remaining` from timestamps

crates/hyperdrive-math/src/long/open.rs
removes old `get_open_long` (which was recently renamed to `calculate_open_long`) fn that has been deprecated since `0.4.0`.
=> removes deprecated `calculate_open_long` function

crates/fixed-point/src/lib.rs, crates/hyperdrive-math/src/lib.rs, crates/hyperdrive-math/src/long.rs, crates/hyperdrive-math/src/long/close.rs, crates/hyperdrive-math/src/long/max.rs, crates/hyperdrive-math/src/long/open.rs, crates/hyperdrive-math/src/lp.rs, crates/hyperdrive-math/src/short.rs, crates/hyperdrive-math/src/short/close.rs, crates/hyperdrive-math/src/short/open.rs, crates/hyperdrive-math/src/utils.rs, crates/hyperdrive-math/src/yield_space.rs, crates/hyperdrive-math/tests/integration_tests.rs, crates/test-utils/src/chain/dev_chain.rs, crates/test-utils/src/chain/test_chain.rs
Addresses one component required for https://github.com/delvtech/hyperdrive/issues/775
- Adds a helper function to calculate the spot rate after a long is opened
- Cleans up rust compiler warnings about unused imports
- Adds an optional `bond_amount` argument to `calculate_spot_price_after_long` to prevent duplicate calls to `open_long` and to better match the signature for `calculate_spot_price_after_short`.
- Removes deprecated `calculate_short_deposit` (used to  be `get_short_deposit`) that has not been recommended since `0.4.0`
I didn't fuzz test this against solidity because it uses the rust open long flow, which is tested against solidity. This follows the same pattern as `calculate_spot_price_after_long`. …
=> add `calculate_spot_rate_after_long` and general cleanup

contracts/src/deployers/ezeth/EzETHHyperdriveDeployerCoordinator.sol, contracts/src/deployers/reth/RETHHyperdriveDeployerCoordinator.sol, contracts/src/instances/ezeth/EzETHBase.sol
https://github.com/spearbit-audits/delv-review/issues/16
To solve this issue we make EzETHHyperdriveDeployerCoordinator's `_getInitialVaultSharePrice()` function's logic mirror that of EzETHBase's `convertToBase()` function. with a `_shareAmount` value of `ONE`, so that it matches how `HyperdriveBase`s `_pricePerVaultShare` logic.  See comparison here:
```ts
// HyperdriveBase
/// @dev Loads the share price from the yield source.
/// @return vaultSharePrice The current vault share price.
function _pricePerVaultShare()
internal
view
returns (uint256 vaultSharePrice)
{
return _convertToBase(ONE);
}
```
```ts
// EzETHHyperdriveDeployerCoordinator
/// @dev Gets the initial vault share price of the Hyperdrive pool.
/// @return The initial vault share price of the Hyperdrive pool.
function …
```
=> getInitialVaultSharePrice uses convertToBase logic

CODEOWNERS
Add Cash and Matt as code owners for directories that are often modified when creating new instances and testing.
=> Add Instance Test owners to CODEOWNERS

.github/workflows/check_diff.yaml
Fixes the `check-diff` github workflow so that it supports `push` events.
=> Fixed the check-diff flow in the case of `push` events

crates/hyperdrive-math/src/lp.rs, crates/hyperdrive-math/src/short/open.rs
https://github.com/delvtech/hyperdrive/issues/927
The `calculate_net_curve_trade` was intermittently failing in CI. The failure was due to a uncommonly entered branch that was missing... another branch... (there are a few nested branching paths).
I was able to consistently see the bug by upping the number of fuzz tests to 100k. I just ran 100k and was not able to see it again, so I'm _pretty sure_ it's fixed. [Here's](https://github.com/delvtech/hyperdrive/blob/4f701159a795a8131fe6e1284b371e8c97218b6b/contracts/src/libraries/LPMath.sol#L356) the relevant solidity code.
referenced in the checklist to make sure that they are reviewed. If …
=> fixes bug in lp net curve trade flow

crates/hyperdrive-math/src/long/close.rs, crates/hyperdrive-math/src/long/open.rs, crates/hyperdrive-math/src/short/close.rs, crates/hyperdrive-math/src/short/fees.rs, crates/hyperdrive-math/src/short/open.rs
https://github.com/delvtech/hyperdrive/issues/743 (partially)
Adds the following error checks in rust trades:
- Minimum transaction checks for all long and short trades.
- Adds negative interest checks for open and close shorts.
be removed.
=> Add error handling to rust trade logic

crates/hyperdrive-math/src/lib.rs, crates/hyperdrive-math/src/lp.rs, crates/hyperdrive-math/src/yield_space.rs
https://github.com/orgs/delvtech/projects/13?pane=issue&itemId=58015840
Adds the rust function `calculate_add_liquidity`
be removed.
=> Add `calculate_add_liquidity` to rust sdk.

crates/hyperdrive-math/src/long.rs, crates/hyperdrive-math/src/long/max.rs, crates/hyperdrive-math/src/long/open.rs, crates/hyperdrive-math/src/long/targeted.rs, crates/hyperdrive-math/tests/integration_tests.rs, crates/test-utils/src/agent.rs
addresses https://github.com/delvtech/hyperdrive/issues/775
The solution first attempts to directly compute targeted reserve levels:
For some target rate, $r_t$, the pool share reserves, $z_t$, must be:
$$
z_t = \frac{1}{\mu} \left(
\frac{k}{\frac{c}{\mu} + \left(
(r_t t + 1)^{\frac{1}{T}}
\right)^{1 - T}}
\right)^{\tfrac{1}{1 - T}}
$$
and the pool bond reserves, $y_t$, must be:
$$
y_t = \left(
\frac{k}{ \frac{c}{\mu} +  \left(
\left( r_t t + 1 \right)^{\frac{1}{T}}
\right)^{1-T}}
\right)^{1-T} \left( r_t t + 1 \right)^{\frac{1}{T}}
$$
where $c$ is the vault share price, $\mu$ is the initial vault share price, $t$ is the annualized position duration, and $T$ is the time stretch constant. The corresponding deltas are then:
$$
\Delta x = c * (z_t - z_e)
$$
$$
\Delta y = y - y_t - c(\Delta …
=> add get_targeted_long

crates/hyperdrive-math/src/long/max.rs, crates/hyperdrive-math/src/long/targeted.rs, crates/hyperdrive-math/src/short/max.rs
intermittent CI crashes; no issue created
CI was crashing with intermittent errors. For example:
```
---- long::targeted::tests::test_calculate_targeted_long_with_budget stdout ----
thread 'long::targeted::tests::test_calculate_targeted_long_with_budget' panicked at crates/hyperdrive-math/src/long/targeted.rs:532:17:
The new_rate=0.065615470865036337 should be <= target_rate=0.040702128765527778 when budget constrained.
failures:
long::targeted::tests::test_calculate_targeted_long_with_budget
test result: FAILED. 33 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 520.83s
```
This particular error was caused by an incorrect sign. In that condition, we expected that the test undershot & should raise an error on the opposite condition (the else condition presumes that we …
=> fix targeted long tests

crates/hyperdrive-math/src/long/max.rs, crates/hyperdrive-math/src/short/max.rs, crates/test-utils/src/agent.rs
General updates towards https://github.com/delvtech/hyperdrive/issues/871
This PR does the following updates:
- Adds a test comparing calculated derivative of `long_amount_derivative` and `short_deposit_derivative` emperically.
- Further work needs to be done here to decrease comparison epsilon
- Adds a test ensuring the absolute max short is a valid short size on chain.
- Implements the max short derivative calculation from https://github.com/delvtech/hyperdrive/pull/733.
- Fixes for the case where the initial max short guess made the pool insolvent.
- Fixes for convergence of `calculate_max_short`.
- ~Increasing the default number of iterations from 7 to 10 for `calculate_max_short`.~ Solved issue where we needed more iterations, so the default number of iterations is not changed. …
=> Fixing `calc_max_short` for accuracy

crates/hyperdrive-math/src/long/open.rs, crates/hyperdrive-math/src/long/targeted.rs, crates/hyperdrive-math/src/short/open.rs
partially addresses https://github.com/delvtech/hyperdrive/issues/955
- The `calculate_open_short` was written at a different time from `calculate_open_long`; I updated it so that they follow the same process.
edit: this caused trouble for reasons I can't explain but probably have to do with share/base conversions. I reverted it, but left some new error stuff.
- I also added some better error checking in `calculate_targeted_long` so that it can safely return in what was previously considered an error state.
- I added a new random test variable, the target rate itself, in the `calculate_targeted_long` tests.
referenced in the checklist to …
=> update calc open short & target long

crates/hyperdrive-math/src/lib.rs, crates/hyperdrive-math/src/lp.rs
- State generation for `long_average_maturity_time` and `short_average_maturity_time` in tests do not cover full range of possible values, due to the underlying fields in pool info being scaled by 1e18.
- Fixing time remaining calculation in `calculate_present_value` to account for average maturity time being scaled.
be removed.
=> Fixing bug in average time remaining calculation in present value

crates/fixed-point/src/lib.rs, crates/hyperdrive-math/src/lib.rs, crates/hyperdrive-math/src/long/open.rs, crates/hyperdrive-math/src/long/targeted.rs, crates/hyperdrive-math/src/short/open.rs, crates/hyperdrive-math/src/yield_space.rs, crates/test-utils/src/bin/migrate.rs, crates/test-utils/src/bin/testnet_deployment.rs
no issues
- removes unused imports
- uses lib calc rate function instead of duplicated fn in targeted_long
- moves reserves_given_rate into lib for use by targeted short
- updates docstrings, var names, & fn names to be more clear
be removed.
=> code cleanup

contracts/src/libraries/FixedPointMath.sol, test/units/libraries/FixedPointMath.t.sol
Removed infeasible branch condition in `calculateWeightedAverage()` per Certora report. This should get fixed point math to 100% coverage.
=> FixedPointMath 100% coverage

contracts/src/internal/HyperdriveShort.sol, crates/hyperdrive-math/src/long/open.rs, crates/hyperdrive-math/src/short/fees.rs, crates/hyperdrive-math/src/short/max.rs, crates/hyperdrive-math/src/short/open.rs, crates/hyperdrive-math/tests/integration_tests.rs, crates/test-utils/src/agent.rs
working towards resolving https://github.com/delvtech/hyperdrive/issues/969
- whenever `calculate_open_short` was called we would first compute `state.calculate_spot_price` and then pass it in as an argument, I removed the argument and put the calculation inside the function. If one wants to calculate open short for a different spot price, they should adjust the state and then call `state.calculate_open_short(bond_amount)`. This is the same pattern we use for e.g. `calc_spot_price_after_*`.
- I renamed a bunch of variables for consistency. Namely, adding "`maybe`" in front of `Option` parameters and changing `short_amount` to `bond_amount`.
- I added public `wallet` and `hyperdrive` attributes to the agent, which will be helpful for the calc_open_short test I'm writing in a follow-up PR. …
=> Rust cleanup; add tests; simplify fn signatures

crates/hyperdrive-math/src/lib.rs, crates/hyperdrive-math/src/short/open.rs, crates/test-utils/src/agent.rs
Fixes: #996.
Adds an implied rate calculation to the Rust SDK.
=> Adds an implied rate calculation to the Rust SDK

contracts/test/MockHyperdriveMath.sol, test/units/libraries/HyperdriveMath.t.sol
This should bump coverage in Hyperdrive Math
=> test negative zeta adjustment

crates/hyperdrive-math/src/short/max.rs, crates/hyperdrive-math/src/short/open.rs
partially addresses https://github.com/delvtech/hyperdrive/issues/937
This PR
- adds a few tests
- makes minor changes to error messaging, doc strings, and variable names
- moves functions from `max.rs` into `open.rs` to make them more accessible for the targeted short function (https://github.com/delvtech/hyperdrive/issues/865)
be removed.
=> Add short::open tests

contracts/src/factory/HyperdriveFactory.sol, contracts/src/interfaces/IHyperdriveFactory.sol, test/instances/erc4626/ERC4626Hyperdrive.t.sol, test/instances/erc4626/ERC4626Validation.t.sol, test/instances/erc4626/UsdcERC4626.t.sol, test/integrations/deployers/ERC4626DeployerCoordinator.t.sol, test/integrations/deployers/RethDeployerCoordinator.t.sol, test/integrations/deployers/StethDeployerCoordinator.t.sol, test/integrations/factory/HyperdriveFactory.t.sol, test/utils/InstanceTest.sol
This PR adds a new role to the factory that can add and remove deployer coordinators. This will provide some flexibility to governance on mainnet so that they can avoid timelocks every time a deployer coordinator is added.
be removed.
token spend?
immutable or …
=> Add the `deployerCoordinatorManager` role to the `HyperdriveFactory`

contracts/src/factory/HyperdriveFactory.sol, contracts/src/factory/HyperdriveRegistry.sol, contracts/src/interfaces/IHyperdriveFactory.sol, contracts/src/interfaces/IHyperdriveGovernedRegistry.sol, contracts/src/interfaces/IHyperdriveRegistry.sol, test/integrations/factory/HyperdriveFactory.t.sol, test/units/HyperdriveRegistry.t.sol, test/utils/Lib.sol
Updates the schema for the registry so that it is more helpful for programmatic users. This PR also updates some inconsistencies in the `HyperdriveFactory` and interfaces throughout the codebase.
be removed.
token spend?
not a …
=> Made the registry more fully-featured

contracts/test/MockERC4626.sol
This helps with testing.  When solidity is called using anvil in rust tests, the block is ticked by 1 second.  Because there is a call to `_getAccruedInterest()` in `totalAssets()`, the only way to get the exact value is to pass the current time plus one second to `totalAssets()`.
be removed.
token spend?
arbitrary addresses, so the list of …
=> Add  `totalAssets(uint256 timestamp)` to MockERC4626

test/utils/HyperdriveUtils.sol
working towards https://github.com/delvtech/hyperdrive-rs/issues/29
The solvency after short check used `divDown` to convert from base to shares, but the open short function uses `divUp`. Therefore it was possible to have the solvency check say "all good" and then open short reverts. This fixes that problem.
I also added some intermediate checks so that the function fails gracefully in more situations.
be removed. …
=> update rounding behavior in `calculateSolvencyAfterShort`

contracts/src/instances/morpho-blue/MorphoBlueBase.sol, test/instances/aave/AaveHyperdrive.t.sol, test/instances/ezETH/EzETHHyperdrive.t.sol, test/instances/lseth/LsETHHyperdrive.t.sol, test/instances/morpho-blue/MorphoBlueHyperdrive.t.sol, test/instances/reth/RETHHyperdrive.t.sol, test/instances/steth/StETHHyperdrive.t.sol, test/instances/susde/SUSDe.t.sol, test/utils/InstanceTest.sol
Fixes: #1105.
To integrate with Ethena's SUSDe instance, we will be using the `ERC4626Hyperdrive` instance contract. To sanity check this idea, this PR adds a comprehensive test suite that can also be used for future ERC4626 integrations.
be removed.
token spend?
immutable or …
=> Tests for the SUSDe Integration

STYLE_GUIDE.md
This PR adds the Minimum Crappy Product of a DELV Solidity Style Guide. This includes the basic elements of our style. It is likely missing many important style rules or heuristics. As we go through future PR review cycles and find things that aren't in the style guide, we should add them along with fixing whatever review feedback arises.
=> Minimum Crappy Style Guide

contracts/src/instances/morpho-blue/MorphoBlueBase.sol, contracts/src/interfaces/IHyperdrive.sol, contracts/src/libraries/Constants.sol
This PR removes any handling of extra data in Morpho.
=> Updated `MorphoBlueHyperdrive` to ignore all extra data

hardhat.config.mainnet.ts, tasks/deploy/config/mainnet/index.ts, tasks/deploy/config/mainnet/morpho-blue-susde-dai-182day.ts, tasks/deploy/config/mainnet/morpho-blue-wsteth-usdc-182day.ts, tasks/deploy/lib/constants.ts, tasks/factory/remove-coordinator.ts
be removed.
token spend?
issues?
=> morpho wsteth usdc mainnet

hardhat.config.gnosis.ts, hardhat.config.ts, scripts/deploy-fork.sh, scripts/deploy.sh, scripts/fund-fork-accounts.sh, tasks/deploy/config/gnosis/chainlink-coordinator.ts, tasks/deploy/config/gnosis/erc4626-coordinator.ts, tasks/deploy/config/gnosis/factory.ts, tasks/deploy/config/gnosis/index.ts, tasks/deploy/config/gnosis/sxdai-182day.ts, tasks/deploy/config/gnosis/wsteth-182day.ts, tasks/deploy/lib/constants.ts, tasks/fork/index.ts, tasks/fork/maintain-rate.ts, tasks/fork/mint-wsteth.ts, tasks/fork/mint-wxdai.ts
Contains configuration for the following items on Gnosis chain:
- Factory
- Delv Registry
- Chainlink Deployer Coordinator
- ERC4626 Deployer Coordinator
- wstETH Hyperdrive instance
- sxDAI Hyperdrive instance
be removed.
token spend?
immutable or tightly controlled by an …
=> add deployment config for gnosis wsteth and sxdai hyperdrives

.github/workflows/build_hyperdrivetypes.yml, .github/workflows/build_types_on_change.yml, .github/workflows/build_types_on_tag.yml, python/hyperdrivetypes/prerequisite.txt, python/hyperdrivetypes/pyproject.toml
This PR changes the `build_hyperdrivetypes.yml` file to be a [reusable workflow](https://docs.github.com/en/actions/sharing-automations/reusing-workflows). We then have two separate actionable workflows that build & ship types if either 1) the hyperdrive version has incremented OR 2) the pyproject.toml version has incremented.
Both of these cases include checks that the first three hyperdrive symver digits (vX.Y.Z) match the first three hyperdrivetypes digits.
=> extract hyperdrivetypes build workflow & use it in two different conditions

.env_template, contracts/src/interfaces/IHyperdriveGovernedRegistry.sol, contracts/src/interfaces/IHyperdriveGovernedRegistryEvents.sol, contracts/src/registry/HyperdriveRegistry.sol, hardhat.config.linea.ts, tasks/deploy/lib/constants.ts, tasks/deploy/registry.ts, tasks/deploy/verify.ts, test/units/registry/HyperdriveRegistry.t.sol, test/units/rewarder/HyperdriveCheckpointSubrewarder.t.sol, test/utils/HyperdriveTest.sol
This PR updates the registry to support deterministic deployments using CREATE3.
=> Registry Updates

deployments.json, hardhat.config.base.ts, tasks/deploy/verify.ts
This PR includes the new addresses for the cbETH deployment to base and some updates needed to get verification working for `ChainlinkHyperdrive` instances.
=> cbETH deployment to Base

pyproject.toml, python/hyperdrivetypes/hyperdrivetypes/__init__.py, python/hyperdrivetypes/hyperdrivetypes/fixedpoint_types.py, python/hyperdrivetypes/prerequisite.txt, python/hyperdrivetypes/pyproject.toml, python/test_hyperdrivetypes.py
Updating hyperdrivetypes:
- Generating new types for pypechain v0.0.43.
- Include conversion functions to/from pypechain and fixed point versions.
- Include new fixedpoint versions of event types used in agent0.
- Includes test for all new fixedpoint types to/from pypechain and fixedpoint types.
=> Hyperdrivetypes events update. Version bump to v1.0.19.6

deployments.json, tasks/deploy/config/mainnet/index.ts, tasks/deploy/config/mainnet/susds-182day.ts
sUSDS was deployed, initialized, and verified in this PR.
=> Deployed sUSDS

python/hyperdrivetypes/prerequisite.txt, python/hyperdrivetypes/pyproject.toml
See https://github.com/delvtech/pypechain/pull/146 for fix
=> Fixes for duplicate references to struct by bumping pypechain version. Includes version bump to v1.0.20.9

contracts/src/internal/HyperdriveShort.sol, test/instances/morpho-blue/MorphoBlue_USDe_DAI_Hyperdrive.t.sol, test/instances/morpho-blue/MorphoBlue_sUSDe_DAI_Hyperdrive.t.sol, test/instances/morpho-blue/MorphoBlue_wstETH_USDA_Hyperdrive.t.sol, test/integrations/hyperdrive/NonstandardDecimals.sol, test/units/hyperdrive/AddLiquidityTest.t.sol, test/units/hyperdrive/OpenShortTest.t.sol, test/utils/InstanceTest.sol
This PR fixes a minor issue with `openShort` that ensures that the amount of shares owned by the pool are always greater than the expected amount. This ensures that the system is always completely solvent. Despite the old pool design making it possible to have small amounts of insolvency, in practice this wasn't an issue because the magnitudes were so small. The following is an analysis of why this wasn't an issue.
Sheng surfaced a failing fuzz test that indicates insolvency on the Morpho Blue wstETH/USDA Hyperdrive pool. After investigating this issue, I noticed that this issue will occur whenever shorts are opened because of the imprecision in converting from shares to base using the vault share price. 
Since this pool already has a fairly large amount of liquidity in it ($10k), it …
=> Fixed the issue with open short

.github/workflows/benchmark.yml, python/gas_benchmarks.py, test/instances/erc4626/ScrvUSD.t.sol
This PR adds an integration for the scrvUSD yield source (ERC4626). It also includes fixes to CI scripts that were hanging.
=> scrvUSD mainnet integration + CI fixes

python/hyperdrivetypes/prerequisite.txt, python/hyperdrivetypes/pyproject.toml
Pinning only minimum version allows Pypechain to upgrade if there's no breaking changes. Bumping hyperdrivetypes version to upload to pypi. This allows more version flexibility downstream.
=> Only pin minimum version of pypechain. Bumping hyperdrivetypes version to 1.0.20.13

tasks/get-rate.ts
CI fix: changed hyperdrive-wasm import in `get-rate.ts` task to be a dynamic import, since hyperwasm is an ESM module which created compatibility issues with Commonjs and caused CI to fail.
=> change hyperwasm import from get-rate to dynamic

contracts/src/matching/HyperdriveMatchingEngineV2.sol, test/units/matching/HyperdriveMatchingEngineV2Test.t.sol
Resolved all the auditor's findings
=> To resolve the auditor's comments on Matching Engine V2

contracts/src/matching/HyperdriveMatchingEngineV2.sol, test/integrations/matching/MatchingEngineV2IntegrationTest.t.sol, test/integrations/matching/MoonwellUSDCMatchingEngineTest.t.sol, test/units/matching/HyperdriveMatchingEngineV2Test.t.sol
Adding more tests to Matching Engine V2
=> Adding more tests to Matching Engine V2
