contracts/src/factory/HyperdriveFactory.sol
crates/test-utils/src/chain/test_chain.rs
test/integrations/factory/HyperdriveFactory.t.sol

Fixes: #844.
This PR implements a feature that annualizes the flat fee in the factory before checking it against the minimum and maximum fee parameters. This allows governance to specify reasonable flat fee parameters for all position durations simultaneously.

Annualized Flat Fees

---

contracts/src/instances/ezeth/EzETHTarget0.sol
contracts/src/instances/steth/StETHTarget0.sol
contracts/src/interfaces/IEzETHHyperdriveRead.sol
test/instances/ezETH/EzETHHyperdrive.t.sol

- return immutable value
- add renzoOracle getter

Add `renzoOracle()` getter

---

pull_request_template.md

This PR adds a template for pull requests that includes a code review checklist. This checklist should be completed by all reviewers before they approve the PR. While this may feel annoying or awkward initially, getting into the habit of going through this checklist will help us to catch more issues during code review rather than in audits.

Added a pull request template

---

.gitmodules

N/A
Remove unused aave v3 git submodule

Remove aave v3 submodule

---

contracts/src/deployers/reth/RETHHyperdriveCoreDeployer.sol
contracts/src/deployers/reth/RETHHyperdriveDeployerCoordinator.sol
contracts/src/deployers/reth/RETHTarget0Deployer.sol
contracts/src/deployers/reth/RETHTarget1Deployer.sol
contracts/src/deployers/reth/RETHTarget2Deployer.sol
contracts/src/deployers/reth/RETHTarget3Deployer.sol
contracts/src/deployers/reth/RETHTarget4Deployer.sol
contracts/src/instances/reth/RETHBase.sol
contracts/src/instances/reth/RETHHyperdrive.sol
contracts/src/instances/reth/RETHTarget0.sol
contracts/src/instances/reth/RETHTarget1.sol
contracts/src/instances/reth/RETHTarget2.sol
contracts/src/instances/reth/RETHTarget3.sol
contracts/src/instances/reth/RETHTarget4.sol
test/instances/reth/RETHHyperdrive.t.sol

Fixes https://github.com/spearbit-audits/delv-review/issues/20 informational feedback
Rocket storage is passed as an immutable contract parameter across our base, deployer, and target contracts. This can be simplified by replacing the `rocketStorage` variable in `RethBase` with a constant. The rocket storage and rETH contracts are not upgradable per Rocket Networks documentation and is safe to make a constant.
https://docs.rocketpool.net/developers/usage/contracts/contracts
If the …

Replace rocketStorage immutable with constant

---

CODEOWNERS

Matt now has ownership over Rust code.

Give Matt codeownership

---

contracts/src/internal/HyperdriveAdmin.sol

- fixes https://github.com/spearbit-audits/delv-review/issues/21
see https://github.com/spearbit-audits/delv-review/issues/21
be removed.
token spend?
issues?
catch …

Cache storage variables that are read multiple times

---

.github/workflows/check_diff.yaml

Updates the `check-diff` workflow to support `merge_groups`.

Update `check_diff` to support `merge_groups`

---

contracts/src/interfaces/IHyperdriveEvents.sol
contracts/src/internal/HyperdriveCheckpoint.sol
test/units/hyperdrive/CheckpointTest.t.sol

While I was working on the fix to [Spearbit Issue #34](https://github.com/spearbit-audits/delv-review/issues/34) yesterday, I noticed two issues with our checkpointing logic. First, we were using the provided `_vaultSharePrice` to `_applyCheckpoint` to mint the checkpoint and to perform all of our accounting logic. This doesn't pass the sniff test since our accounting logic uses the open vault share price, the close vault share price, and the current vault share price in general. I originally noticed this when thinking about the vault share price being provided to `_distributeExcessIdleSafe`, and then I noticed some even more egregious cases involving the accounting logic used to decide the base proceeds to reserve for matured longs and shorts. Second, we weren't performing a linear …

Fixed a couple of checkpointing bugs

---

contracts/src/deployers/HyperdriveDeployerCoordinator.sol
test/integrations/deployers/DeployerCoordinator.t.sol

- fixes https://github.com/spearbit-audits/delv-review/issues/26
The effective salt provided for deploying targets 1-4 is currently not hashed with other parameter to prevent-front running DoS/griefing attacks. Include msg.sender and deploymentId in the "salt".
be removed.
token spend?
arbitrary addresses, so the list of possible …

use msg.sender,deploymentId in target deployment addresses

---

contracts/src/internal/HyperdriveLP.sol
contracts/src/libraries/LPMath.sol
contracts/src/libraries/YieldSpaceMath.sol
contracts/test/MockLPMath.sol
test/units/libraries/LPMath.t.sol

- fixes https://github.com/spearbit-audits/delv-review/issues/22
Some paths in `_distributeExcessIdleSafe` are not safe, they should be. See https://github.com/spearbit-audits/delv-review/issues/22 for more details.
be removed.
token spend?
immutable or tightly …

fix unsafe routes in _distributeExcessIdleSafe

---

contracts/src/libraries/SafeCast.sol
contracts/test/MockSafeCast.sol
test/units/libraries/SafeCast.t.sol

Fixes https://github.com/spearbit-audits/delv-review/issues/23
Optimized the `SafeCast` library and added some test coverage.
be removed.
token spend?
issues?
catch …

Optimized the `SafeCast` library

---

codegen/templates/instances/Base.sol.jinja
contracts/src/deployers/ezeth/EzETHHyperdriveDeployerCoordinator.sol
contracts/src/deployers/lseth/LsETHHyperdriveDeployerCoordinator.sol
contracts/src/deployers/reth/RETHHyperdriveDeployerCoordinator.sol
contracts/src/instances/ezeth/EzETHBase.sol
contracts/src/instances/lseth/LsETHBase.sol
contracts/src/instances/reth/RETHBase.sol
contracts/test/MockHyperdrive.sol

- fixes https://github.com/spearbit-audits/delv-review/issues/28
- use the same logic for checking msg.value across all contracts
be removed.
token spend?
issues? …

standardize checks for msg.value

---

contracts/src/libraries/LPMath.sol
contracts/test/MockLPMath.sol
test/units/libraries/LPMath.t.sol

fixes https://github.com/spearbit-audits/delv-review/issues/18
Returns an error when `rhs == ONE` however it can successfully return 0 here.
be removed.
token spend? …

calculateSharesDeltaGivenBondsDeltaDerivativeSafe edge case

---

contracts/src/factory/HyperdriveFactory.sol

Fixes: https://github.com/spearbit-audits/delv-review/issues/19
Removes a few unnecessary assignments from the `HyperdriveFactory.`
be removed.

Removed unnecessary assignment from the `HyperdriveFactory`

---

contracts/src/libraries/LPMath.sol

Spearbit Issue [#17](https://github.com/spearbit-audits/delv-review/issues/17)
This fixes a documentation issue introduced in the previous fix PR.

Fix for Spearbit #17

---

contracts/test/MockLPMath.sol
test/units/libraries/LPMath.t.sol

This PR should cover all branches for `calculateDistributeExcessIdleShareProceedsNetLongEdgeCaseSafe()`

coverage for calculateDistributeExcessIdleShareProceedsNetLongEdgeCaseSafe

---

.github/workflows/benchmark.yml
.github/workflows/codegen_test.yml
.github/workflows/coverage.yml
.github/workflows/rust_lint.yml
.github/workflows/rust_test.yml
.github/workflows/solidity_lint.yml
.github/workflows/solidity_test.yml
.gitignore
foundry.toml
scripts/coverage.sh
test/units/MultiToken.t.sol
test/units/hyperdrive/RedeemWithdrawalSharesTest.t.sol

- Added missing external tests
- unpin foundry
- add coverage script

external coverage to 100% and coverage config tweaks

---

contracts/src/internal/HyperdriveLong.sol
test/integrations/hyperdrive/IntraCheckpointNettingTest.t.sol

This PR adds a solvency guard to `closeLong` to fix a problem discovered earlier today. Big h/t to @slundqui for the find.
be removed.
token spend?
issues?
catch …

Fixed the solvency bug

---

contracts/src/deployers/erc4626/ERC4626HyperdriveCoreDeployer.sol
contracts/src/deployers/ezeth/EzETHHyperdriveCoreDeployer.sol
contracts/src/deployers/lseth/LsETHHyperdriveCoreDeployer.sol
contracts/src/deployers/steth/StETHHyperdriveCoreDeployer.sol

add return variables to increase coverage

coverage increase for deployers

---

test/integrations/factory/HyperdriveFactory.t.sol
test/units/libraries/YieldSpaceMath.t.sol

This PR covers an invalid deployer coordinator case that is untested and a InsufficientLiquidity revert in YS Math

misc coverage increase

---

contracts/test/MockLPMath.sol

Adds helper methods that we can test.  Adding in it's own PR here since the rust code will now live in hyperdrive-rs and this needs to land first.
be removed.
token spend?
memory …

Add functions to MockLPMath

---

contracts/test/MockERC4626.sol

This PR makes the `maxMintAmount` mutable and adds an unrestricted flow for minting. This will fix the problems that we've seen on testnet with the sDAI vault.
be removed.
token spend? …

Fixed the `MockERC4626` vault

---

README.md

Related to https://github.com/delvtech/hyperdrive-frontend/issues/1027

Update terms URL

---

cSpell.json
contracts/test/MockERC4626.sol
package.json
test/debug/Debugging.t.sol
test/utils/EtchingUtils.sol

This PR cherry-picks some changes from the original deployment branch (`jalextowle/testnet/deployment`) that never made it into main. These changes ensure that `sDAI` has a stable share price when assets are minted.
be removed.
token spend?
immutable or tightly …

Fixed the sDAI vault

---

test/units/libraries/YieldSpaceMath.t.sol

increase coverage for yieldspace math

---

contracts/src/interfaces/IHyperdriveEvents.sol
contracts/src/internal/HyperdriveAdmin.sol
contracts/src/internal/HyperdriveBase.sol
contracts/src/internal/HyperdriveLP.sol
contracts/src/internal/HyperdriveLong.sol
contracts/src/internal/HyperdriveShort.sol
test/units/hyperdrive/AddLiquidityTest.t.sol
test/units/hyperdrive/CloseLongTest.t.sol
test/units/hyperdrive/CloseShortTest.t.sol
test/units/hyperdrive/FeeTest.t.sol
test/units/hyperdrive/InitializeTest.t.sol
test/units/hyperdrive/OpenLongTest.t.sol
test/units/hyperdrive/OpenShortTest.t.sol
test/units/hyperdrive/RedeemWithdrawalSharesTest.t.sol
test/units/hyperdrive/RemoveLiquidityTest.t.sol
test/utils/HyperdriveTest.sol

Updated the event schema so that it is more feasible to recreate the state using events.
be removed.
token spend?
issues?
overflows caught so that a …

Updated the event schema

---

contracts/src/interfaces/IHyperdriveEvents.sol
test/utils/HyperdriveUtils.sol

Renames the fields that were missed in the previous PR and adjusts the logic in `test/utils/HyperdriveUtils.sol` to avoid intermittent failures in the Rust tests.
be removed.
token spend?
not a concern or how it's …

fix: Event Schema

---

contracts/src/libraries/Constants.sol

update hyperdrive version to 1.0.7

---

Makefile
README.md
hardhat.config.ts
scripts/deploy.sh
tasks/deploy/hyperdrive.ts
tasks/deploy/lib/environment-extensions.ts
tasks/deploy/lib/types.ts
tasks/deploy/verify.ts

- runs verify after deploy for live networks
- ensures the repository is up to date with the latest remote tag before deploying to live networks
- adds make command + documentation
be removed.

unified deployment + verification scripting

---

contracts/test/MockERC4626.sol
contracts/test/MockEzEthPool.sol
contracts/test/MockLido.sol
contracts/test/MockRocketPool.sol

Ignores underflows in the mock yield sources.
be removed.
token spend?
issues?
covering the full input …

MockERC4626 Fix

---

contracts/src/interfaces/IHyperdriveEvents.sol
contracts/src/internal/HyperdriveLP.sol
contracts/src/internal/HyperdriveLong.sol
contracts/src/internal/HyperdriveShort.sol

The purpose of this PR is to expose the extra data to the event logs. The following functions have been updated:
- open/close long
- open/close short
- add/remove liquidity
- intialize
- redeemwithdrawal shares
be removed.
token spend?
immutable or tightly controlled by an …

add extra data to event logs

---

test/integrations/hyperdrive/SandwichTest.t.sol

Adds testing for the LP sandwich attack to ensure that the initial LP will not lose money with a properly configured circuit breaker delta.
be removed.
token spend?
issues?
catch …

LP Sandwich Tests

---

contracts/src/libraries/Constants.sol

be removed.
token spend?
issues?

Update version to v1.0.9

---

contracts/src/internal/HyperdriveCheckpoint.sol
test/units/hyperdrive/CheckpointTest.t.sol

This PR fixes an infinite loop that could occur in the checkpoint flow when checkpointing a past checkpoint when the latest checkpoint hadn't been minted. This could have prevented matured positions from a previous checkpoint from being closed (but this could have been recovered by minting the latest checkpoint).
be removed.
token spend? …

Fixed an infinite loop in the checkpoint flow

---

contracts/src/libraries/Constants.sol

be removed.
token spend?
issues?

Version bump to v1.0.10

---

deployments.json
tasks/deploy/verify.ts

- Deployed new version of registry on sepolia
- Verify registry in verification script

deploy new sepolia registry

---

contracts/src/internal/HyperdriveLong.sol
contracts/src/internal/HyperdriveShort.sol

Fixes: https://github.com/spearbit-audits/delv-week-review/issues/4.
Caches the result of `_effectiveShareReserves()` in `HyperdriveLong` and `HyperdriveShort`.
be removed.
token spend?
memory …

Caches the result of `_effectiveShareReserves()` in more places

---

contracts/src/internal/HyperdriveCheckpoint.sol
contracts/src/internal/HyperdriveLong.sol
contracts/src/internal/HyperdriveShort.sol

Fixes: https://github.com/spearbit-audits/delv-week-review/issues/11
This PR simplifies `_applyCheckpoint`.
be removed.
token spend?
issues?
overflows caught so …

Simplified `_applyCheckpoint`

---

contracts/src/libraries/FixedPointMath.sol
contracts/src/libraries/LPMath.sol
contracts/test/MockFixedPointMath.sol
test/units/libraries/FixedPointMath.t.sol

Fixes: https://github.com/spearbit-audits/delv-week-review/issues/10
Used `openzeppelin`'s `abs` function. This addresses the concern from the issue without resorting to returning an invalid value.
be removed.
token spend?
not a …

Jalextowle/audit 06 10 2024/spearbit 10

---

scripts/pause.sh

Part of #980. This PR defines a batch pauser script that reads from the registry and pauses all active pools.

add pauser script

---

contracts/src/libraries/Constants.sol
contracts/test/MockLido.sol
test/instances/steth/Sweep.t.sol

Fixes: #799.
After some issues were encountered with the agent0 fuzzing that used the `MockLido` vault, it became apparent that the current methodology used by the `MockLido` vault wasn't acceptable. This PR rewrites the mock yield source so that we can continue fuzzing the stETH integration.
be removed.
token spend?
arbitrary addresses, so the …

Re-wrote the `MockLido` contract to store its balances as shares

---

README.md
deployments.json
scripts/deploy.sh
tasks/deploy/config/anvil/erc4626-coordinator.ts
tasks/deploy/config/anvil/erc4626-hyperdrive.ts
tasks/deploy/config/anvil/factory.ts
tasks/deploy/config/anvil/steth-coordinator.ts
tasks/deploy/config/anvil/steth-hyperdrive.ts
tasks/deploy/verify.ts
tasks/registry/add.ts

Adds the mainnet addresses after deployment.

Adds the mainnet addresses

---

STYLE_GUIDE.md

be removed.
token spend?
issues?

add some guidance around tests

---

tasks/deploy/config/mainnet/morpho-blue-susde-dai-182day.ts

Change the initial fixed rate to 9.8% to match updated market rate. Change the circuit breaker delta to 7.5% to match the rules in the Operations Playbook

change susde-dai config params

---

deployments.json
tasks/deploy/verify.ts

be removed.
token spend?
issues?

morpho susde dai deploy

---

cSpell.json
test/utils/EtchingUtils.sol

Wires up `MorphoBlueHyperdrive` in the etching utils.

Adds MorphoBlue to the etching tools

---

tasks/deploy/config/gnosis/sxdai-182day.ts
tasks/deploy/config/gnosis/wsteth-182day.ts

sxDai yield on gnosis chain is over 7% 
https://defillama.com/yields/pool/13392973-be6e-4b2f-bce9-4f7dd53d1c3a

change initial fixed rate to 7%

---

CODEOWNERS

Added Dylan and Sheng as global codeowners

---

contracts/src/instances/rseth-linea/RsETHLineaConversions.sol
deployments.json
scripts/deploy.sh
tasks/deploy/config/linea/ezeth-linea-182day.ts
tasks/deploy/config/linea/rseth-linea-182day.ts
tasks/deploy/verify.ts

This PR includes any changes required to deploy ezETH and rsETH to Linea and the deployed addresses.

EzETH and RsETH deployment to Linea

---

contracts/src/interfaces/IFiatTokenProxy.sol
hardhat.config.base.ts
tasks/deploy/config/base/index.ts
tasks/deploy/config/base/morpho-blue-cbeth-usdc-182day.ts
tasks/deploy/config/base/morpho-blue-coordinator.ts
tasks/deploy/lib/constants.ts
test/instances/morpho-blue/MorphoBlue_cbETH_USDC_Base_Hyperdrive.t.sol
test/instances/morpho-blue/MorphoBlue_wstETH_USDC_Hyperdrive.t.sol

This PR adds a test suite and deployment tools for the Morpho Blue cbETH/USDC pool on Base.

Morpho Blue cbETH/USDC Integration on Base

---

deployments.json
hardhat.config.base.ts
tasks/deploy/verify.ts

This PR fixed an issue with verification and deployed and verified the Morpho cbETH/USDC pool.

Deployed the Morpho cbETH/USDC pool on base

---

contracts/src/interfaces/IMetaMorpho.sol
hardhat.config.base.ts
tasks/deploy/config/base/erc4626-coordinator.ts
tasks/deploy/config/base/index.ts
tasks/deploy/config/base/moonwell-eth-182day.ts
tasks/deploy/lib/constants.ts
test/instances/erc4626/MetaMorphoHyperdriveInstanceTest.t.sol
test/instances/erc4626/MoonwellETH.t.sol

Added the Moonwell ETH vault

---

CODEOWNERS

Remove John, Dylan, and Sheng and add Sean to the list of codeowners

Updated the list of codeowners
